### ISSUE TITLE
No module named 'cv2'

### ISSUE THREAD

**Issue by VivoNeuro** [kushalkolar/MESmerize#52]
Hello,
I have just started to use Mesmerize. I tried to run the motion correction (Batch Manager window/Start) and it gave me the following error:
Traceback (most recent call last):
  File "c:\programdata\anaconda3\envs\mesmerize\lib\site-packages\mesmerize\viewer\modules\batch_run_modules\caiman_motion_correction.py", line 18, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'
Could you help me with it? Thank you! (Win10)

**Comment by kushalkolar** [comment]
Is your system configuration setup properly? See the notes after the
installation instructions.

**Comment by EricThomson** [comment]
@VivoNeuro I had the same problem, and had to uncomment `conda activate mesmerize` in the config file (after Kushal helped me fix a problem with getting the config file working: https://github.com/kushalkolar/MESmerize/issues/53). Note fwiw when using caiman on my machine I tend to get better performance when I set the number of processes quite a bit fewer than the max (on my machine I have 55 cores, and I set it to 10 typically when using caiman otherwise I start getting pretty sluggish behavior b/c RAM).

**Comment by kushalkolar** [comment]
@EricThomson Yea the optimal number of cores for your setup will vary depending on the type of data that you have, available RAM, and possibly RAM speed as well, and if you have NUMA nodes without direct access to the RAM.
